"use client";

import React, { useState } from "react";
import shajs from "sha.js";
import SimpleCard from "../../../../../components/card/SimpleCard";
import Label from "../../../../../components/form/Label";
import PageTitle from "../../../../../components/typography/PageTitle";
import Input from "../../../../../components/form/Input";
import Select from "../../../../../components/form/Select";
import Option from "../../../../../components/form/Option";

enum ShaType {
  SHA = "sha",
  SHA1 = "sha1",
  SHA224 = "sha224",
  SHA256 = "sha256",
  SHA384 = "sha384",
  SHA512 = "sha512",
}

export default function ToolShaPage() {
  const [type, setType] = useState<ShaType>(ShaType.SHA);
  const [input, setInput] = useState<string>("");

  const onChangeType = (e: React.ChangeEvent<HTMLSelectElement>) => {
    setType(e.target.value as ShaType);
  };

  const onChangeInput = (e: React.ChangeEvent<HTMLInputElement>) => {
    setInput(e.target.value);
  };

  return (
    <>
      <PageTitle>Sha Tool</PageTitle>

      <Label label="Input">
        <Input onChange={onChangeInput} value={input} />
      </Label>

      <Label label="Algorithm">
        <Select onChange={onChangeType} value={type}>
          <Option value={ShaType.SHA}>SHA</Option>
          <Option value={ShaType.SHA1}>SHA-1</Option>
          <Option value={ShaType.SHA224}>SHA-224</Option>
          <Option value={ShaType.SHA256}>SHA-256</Option>
          <Option value={ShaType.SHA384}>SHA-384</Option>
          <Option value={ShaType.SHA512}>SHA-512</Option>
        </Select>
      </Label>

      <SimpleCard>{shajs(type).update(input).digest("hex")}</SimpleCard>

      <SimpleCard>
        The tool is a SHA hash calculator that helps you calculate the SHA,
        SHA1, SHA224, SHA256, SHA384, and SHA512 values of a string. It is
        designed to help you generate secure and unique hashes of strings,
        making it ideal for security and cryptography applications. The tool
        takes a string as input and generates the corresponding SHA, SHA1,
        SHA224, SHA256, SHA384, and SHA512 hash values as output. The hashes
        generated by the tool are cryptographic hashes, meaning they are
        designed to be unique and secure. They can be used for a variety of
        purposes, including password storage, digital signatures, and data
        integrity checks. Whether you&apos;re a developer, security expert, or
        simply need to generate secure hashes for your data, this tool is a
        must-have tool for your toolkit. With its simple and intuitive
        interface, you can quickly and easily generate SHA, SHA1, SHA224,
        SHA256, SHA384, and SHA512 hash values for any string.
      </SimpleCard>
    </>
  );
}
